
--Esto es un comentario
/*Esto tambien 
pero puede ir en muchas lineas*/

CREATE DATABASE  KIOTISFRAGVEN

USE KIOTISFRAGVEN 

CREATE TABLE EMPLEADOS(
NOMBRE VARCHAR(40) UNIQUE NOT NULL,
EDAD INT CHECK(EDAD LIKE '[2-6][0-9]') NOT NULL,
SEXO VARCHAR(1) CHECK(SEXO='F' OR SEXO='M') NOT NULL,
TEL VARCHAR(12),
ANTIG INT,
PUESTO VARCHAR(20) CHECK(PUESTO='CAJERO' OR PUESTO='GEGERENTE'  OR PUESTO='ADMINISTRADOR'  OR PUESTO='INTENDENCIA')  ,
CVEMP INT PRIMARY KEY
)

CREATE TABLE LIBROS(
NOMLIB VARCHAR(60)NOT NULL,
TIPO VARCHAR(20) UNIQUE NOT NULL,
EXISTENCIAS INT DEFAULT(0),
PRECIOVTA MONEY DEFAULT(0),
CVELIB INT PRIMARY KEY
)

CREATE TABLE VENTAS(
FECHAVTA DATE DEFAULT(GETDATE()),
SUBTOTAL MONEY DEFAULT(0),
IVA MONEY DEFAULT(0),
CVENTA INT PRIMARY KEY
)

CREATE TABLE EMPVTAS(
CVEMP INT FOREIGN KEY REFERENCES EMPLEADOS NOT NULL,
CVEVTA INT FOREIGN KEY REFERENCES VENTAS NOT NULL,
)

CREATE TABLE DETVTALIB(
CVELIB INT FOREIGN KEY REFERENCES LIBROS NOT NULL,
CVEVTA INT FOREIGN KEY REFERENCES VENTAS NOT NULL,
CANVTA INT CHECK(CANVTA>0) NOT NULL
)