
--Esto es un comentario
/*Esto tambien 
pero puede ir en muchas lineas*/

CREATE DATABASE  KIOTISFRAGCOM

USE KIOTISFRAGCOM 

CREATE TABLE EDITORIAL(
NOMBREDIT VARCHAR(20) UNIQue NOT NULL,
CVEDIT INT PRIMARY KEY NOT NULL
)

CREATE TABLE LIBROS(
NOMLIB VARCHAR(60)NOT NULL,
TIPO VARCHAR(20) UNIQUE NOT NULL,
EXISTENCIAS INT DEFAULT(0),
PRECIOCOMP MONEY DEFAULT(0),
PRECIOVTA MONEY DEFAULT(0),
GANANCIA MONEY DEFAULT(0),
EDOLIB INT DEFAULT(1),
CVELIB INT PRIMARY KEY,
CVEDIT INT FOREIGN KEY REFERENCES EDITORIAL
)

CREATE TABLE COMPRAS(
FECHACOMP DATE DEFAULT(GETDATE()),
TOTALCOMP MONEY DEFAULT(0),
CVECOMP INT PRIMARY KEY
)

CREATE TABLE PROVEEDORES(
NPROV VARCHAR(30) UNIQUE NOT NULL,
TELP VARCHAR(12),
LOCALIDAD VARCHAR(30),
EDO VARCHAR(20),
CVEPROV INT IDENTITY(1,10) PRIMARY KEY--Con el identity se comienza en 1 y se incrementa de 10 en 10
)

CREATE TABLE LIBROPROV(
CVELIB INT FOREIGN KEY REFERENCES LIBROS NOT NULL,
CVEPROV INT FOREIGN KEY REFERENCES PROVEEDORES NOT NULL
)

CREATE TABLE DETCLIB(
CVELIB INT FOREIGN KEY REFERENCES LIBROS NOT NULL,
CVECOMP INT FOREIGN KEY REFERENCES COMPRAS NOT NULL,
CANCOM INT NOT NULL
)
